name: bonfire
description: (RPG maker) Create RPG-style or similar games more simply with Flame.
version: 0.9.0
homepage: https://github.com/RafaelBarbosatec/bonfire

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^0.29.3
  ordered_set: ^2.0.1
  tiledjsonreader: ^0.0.8
  http: ^0.13.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
